### ISSUE TITLE
不支持导入包的别名吗

### ISSUE THREAD

**Issue by kangour** [Xuanwo/gg#13]
您好呀，我遇到了一个麻烦，希望帮我解答疑惑。
我使用如下语句为包设置一个别名时，得到一个导入错误的提示。
导入语句：

`
	f.NewImport().AddPath("myResponse \"http_server/response\"")
`

错误信息：
`
panic: 8:8:
invalid import path: "myResponse \"http_server/response\""
`

包含空格，或者转义字符时，会报错。

**Comment by Xuanwo** [comment]
可以使用 `f.NewImport().AddAlias()`

https://github.com/Xuanwo/gg/blob/0c3192064fea1c382fbdf3ccd7ae409929749e95/import.go#LL48C21-L48C21

**Comment by kangour** [comment]
谢谢啦，是否可以整理一个完整的文档，包括生成后的代码保存到文件或者在文件制定未知插入这些。另外 gg.group struct 可以改成 gg.Group 吗，我想把生成 group 的函数独立开，只返回一个 group 类型的对象。

类似于这样：
`
func GenCode() *gg.Group {
	f := gg.NewGroup()
	// do something
	return f
}
`

**Comment by Xuanwo** [comment]
> 谢谢啦，是否可以整理一个完整的文档，包括生成后的代码保存到文件或者在文件指定位置插入，替换这些。

> 另外 gg.group struct 可以改成 gg.Group 吗，我想把生成 group 的函数独立开，只返回一个 *gg.Group 类型的对象。

本项目使用 Apache 2.0 协议授权，可以自行 Fork 后修改～
